# Organization of the different stages and jobs:
# build:
#  |_ functional-test (functional tests)
#  |_ notebook-test (notebook tests)
#  |_ py-pytest (Python unit tests)
#  |_ sphinx-build (documentation)
#
# test:
#  |_ py-black (Python code formatting)
#  |_ py-mypy (static type checking with Mypy)
#  |_ py-lint (static analysis with Pylint)
#  |_ py-trivy (dependency scanning)
#  |_ sonar (SonarQube analysis)

spec:
  # Define input parameters for the TBC pipeline.
  inputs:
    # Test stage definition.
    # The python stage (py-pytest) is implicit and included by default.
    test-functional:
      type: boolean
      default: true
---
include:
  - component: $CI_SERVER_FQDN/to-be-continuous/python/gitlab-ci-python@8.6.0  # TBC Python component version
    # Default stage for jobs is build.
    # Below is the list of items to contains.
    inputs:
      image: ${UL_ARTIFACTORY_HOST}/publicremotes-docker/python:3.10
      pytest-enabled: true
      pylint-enabled: true
      black-enabled: false
      mypy-enabled: false
      build-system: setuptools
      # Install pandora2d test dependencies (see setup.cfg file)
      extra-deps: test
  - component: $CI_SERVER_FQDN/to-be-continuous/sonar/gitlab-ci-sonar@5.0.1
    inputs:
      host-url: "${UL_SONARQUBE_URL}"
      quality-gate-enabled: true
  - component: $CI_SERVER_FQDN/to-be-continuous/sphinx/gitlab-ci-sphinx@1.5.0
    inputs:
      image: ${UL_ARTIFACTORY_HOST}/ghcr.io/sphinx-doc/sphinx-ci:latest
      project-dir: doc
    
variables:
  # default production ref name (pattern)
  PROD_REF: /^(master|main)$/
  # default integration ref name (pattern)
  # Decomment to add new branch TickerNumber-XXX
  #INTEG_REF: /^(develop|release|TickerNumber-XXX)$/
  INTEG_REF: /^(develop|release)$/

  # LibSGM's branch to integrate with
  # Override from pipeline GUI/Schedule if needed
  LIBSGM_BRANCH: release

  # Python
  PIP_INDEX_URL: "https://${PANDORA_ARTIFACTORY_USERNAME}:${PANDORA_ARTIFACTORY_KEY}@${UL_ARTIFACTORY_HOST}/artifactory/api/pypi/pypi/simple"
  # Runs Pylint only on the following directories
  PYLINT_FILES: pandora_plugin_libsgm tests

  # Tests
  TEST_FUNCTIONAL: $[[ inputs.test-functional ]]

  # Pandora's branch to integrate with
  # Override from pipeline GUI/Schedule if needed
  PANDORA_BRANCH: release

# Default configuration for all jobs
default:
  tags:
    - Usine_Logicielle

py-black:
  stage: test

py-mypy:
  stage: test
  variables:
    PYTHON_EXTRA_DEPS: dev

py-lint:
  stage: test

# Override to restrict scope of PIP_OPT redefinition
# Cf issue https://gitlab.com/to-be-continuous/sphinx/-/issues/4
.sphinx-base:
  variables:
    # The image follow PEP 668
    PIP_OPTS: "--break-system-packages"

# Set the version of LibSGM to use
libsgm-version:
  stage: .pre
  image: $PYTHON_IMAGE
  extends: .python-base
  script:
    # Use CI job token to authenticate
    - echo "LIBSGM_BRANCH=$LIBSGM_BRANCH"
    - sed -i "s#libsgm[>=<].*#libsgm @ git+https://gitlab-ci-token@${CI_SERVER_HOST}/dali/PandoraBox/libsgm.git@${LIBSGM_BRANCH}#" setup.cfg
  artifacts:
    paths:
      - setup.cfg
  rules:
    # Run this job only if LIBSGM_BRANCH is valued
    - if: $LIBSGM_BRANCH

# Override to use the Makefile rules
py-pytest:
  script:
    # ${TRACE+-d} define the log level
    # Install in editable mode to compute coverage
    - make ${TRACE+-d} test

# Functional tests
functional-test:
  extends: py-pytest
  script:
    # ${TRACE+-d} define the log level
    # Install in editable mode to compute coverage
    - make ${TRACE+-d} test-functional
  artifacts:
    paths:
      - reports/py-coverage-functional.cobertura.xml
  rules:
    # exclude if $TEST_FUNCTIONAL not set
    - if: '$TEST_FUNCTIONAL != "true"'
      when: manual
      allow_failure: true
    - !reference [.test-policy, rules]

notebook-test:
  extends: py-pytest
  script:
    - apt-get update && apt-get install -y cmake
    - git clone --branch "$PANDORA_BRANCH" https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/dali/PandoraBox/pandora.git
    - make ${TRACE+-d} install
    - pip uninstall -y pandora
    - cd pandora
    - pip install meson-python meson ninja setuptools_scm setuptools wheel
    - pip install --no-build-isolation --editable .[dev,notebook]
    - make ${TRACE+-d} test-notebook
  rules:
    - if: $PANDORA_BRANCH

# GitHub push
github-sync:
  stage: .post
  image:
    name: ${UL_ARTIFACTORY_HOST}/publicremotes-docker/alpine/git
    entrypoint: [""]
  variables:
    # Ensure we fetch enough history before pushing it
    GIT_DEPTH: 100
  before_script:
    # Add Cnes certificates
    - mkdir /usr/local/share/ca-certificates/
    - cat ${CNES_CERTIFICATE} > /usr/local/share/ca-certificates/my-cert.crt
    - cat /usr/local/share/ca-certificates/my-cert.crt >> /etc/ssl/certs/ca-certificates.crt
  script:
    - echo "CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME"
    - echo "GITHUB_URL=$GITHUB_URL"
    - echo "CI_COMMIT_SHA=$CI_COMMIT_SHA"
    - git remote add github https://${PANDORA_CNES_GITHUB_TOKEN_USERNAME}:${PANDORA_CNES_GITHUB_TOKEN_PASSWORD}@${GITHUB_URL}
    - git fetch origin ${CI_COMMIT_SHA}
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        git push github $CI_COMMIT_TAG
      else
        git checkout -B ${CI_COMMIT_REF_NAME}
        git push github ${CI_COMMIT_REF_NAME}
      fi
  rules:
    # run on production and integration branches + release pipelines
    - if: '$CI_COMMIT_TAG'
    - !reference [.delivery-policy, rules]
